version: "3.7"

services:
  app:
    build: ./
    ports:
      - 80:8080
    volumes:
      - ./:/app
    environment:
      - TZ=Russia/Moscow
  redis:
    image: redis:5.0.13
    volumes:
      - redis:/data
    environment:
      - TZ=Russia/Moscow

volumes:
  redis: